### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp2019/goTorr#1]
Drage kolege,

Ako je sve gotovo, molim napravite novi Release i tagujte verziju po sistemu na koji ste navikli.

**Comment by anticdimi** [comment]
Ostale su jos neke stvari koje moramo da istestiramo sto se tice komunikacije preko mreze.
Bice sve gotovo preko vikenda, do nedelje uvece cemo napraviti novi Release.

**Comment by anticdimi** [comment]
Dodat release. :)
