### ISSUE TITLE
Ime repozitorijuma

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp2019/goTorr#2]
Drage kolege,

Promenio sam ime repozitorijuma (sada se koristi pravo ime) - cisto da znate ukoliko ste negde koristili linkove ka repozitorijumu. Dao sam ime P2P, ako zelite neko drugo, samo odgovorite ovde i promenicu. U protivnom samo zatvorite issue.

**Comment by anticdimi** [comment]
Sto se tice imena, Anotorr bi bilo okej :)

**Comment by ivan-ristovic** [comment]
Promenjeno.
